### ISSUE TITLE
Get rid of docker/backend and switch to pure frontend js only with graphql/web3

### ISSUE THREAD

**Issue by posix4e** [humanprotocol/escrow-dashboard#17]

**Comment by vkomodey** [comment]
What is the reason of getting rid from docker here? It is already a pure frontend.js application which may be running without docker. The docker wrapper here is only for deployment purposes

**Comment by posix4e** [comment]
Let’s get rid of it in deployment, so the deployment doesn’t require docker at all. Just a tiny bit of js

**Comment by vkomodey** [comment]
By getting rid of the docker we will just move the phase of starting the app in the prod to a different place: this includes webpack build, serving instructions + some tools for monitoring the state of the app(in this case it is a docker, but it might be the pm2 or any other tool which controls the state). We definitely don't want to use bare "yarn start" and control this manually on remote machines

Also, just for the notice - there is no backend(except the server which serves static files) in the dashboard

Regarding pure js. Considering all features that we are planning to add to the dashboard in the future, I won't advise moving it to the pure js, because the code will be messy and hard to read imho

cc @makarofalex3 @ivhus

**Comment by ivhus** [comment]
docker ≠ backend

getting rid of backend would be nice (but as @vkomodey said there is no backend)

Docker container is portable thing which works same in ECS, EKS, Openshift, locally, wherever in any other environment

And with switchng to pure JS we are going to get dependent on the environment and it's confuguration consistency will yet another thing to maintain
